// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PexIM.Models;

namespace PexIM.Migrations
{
    [DbContext(typeof(PexIMContext))]
    [Migration("20201117213614_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PexIM.Models.Estados", b =>
                {
                    b.Property<int>("CodEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NomeEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiglaEstado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("PexIM.Models.Grupo", b =>
                {
                    b.Property<int>("CodGrupo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodGrupo");

                    b.ToTable("Grupo");
                });

            modelBuilder.Entity("PexIM.Models.Imobiliarias", b =>
                {
                    b.Property<int>("CodImobiliaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CodImobiliariaApi")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodImobiliaria");

                    b.ToTable("Imobiliarias");
                });

            modelBuilder.Entity("PexIM.Models.ImobiliariasEstados", b =>
                {
                    b.Property<int>("CodImobiliariaEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CodEstado")
                        .HasColumnType("int");

                    b.Property<int?>("CodImobiliaria")
                        .HasColumnType("int");

                    b.HasKey("CodImobiliariaEstado");

                    b.ToTable("ImobiliariasEstados");
                });

            modelBuilder.Entity("PexIM.Models.Imoveis", b =>
                {
                    b.Property<int>("CodImovel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("AreaPrivativa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AreaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Banheiro")
                        .HasColumnType("int");

                    b.Property<bool>("Churrasqueira")
                        .HasColumnType("bit");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodEstado")
                        .HasColumnType("int");

                    b.Property<int>("Dormitorios")
                        .HasColumnType("int");

                    b.Property<int>("Garagem")
                        .HasColumnType("int");

                    b.Property<int>("Suite")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodImovel");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("PexIM.Models.Usuarios", b =>
                {
                    b.Property<int>("CodUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodGrupo")
                        .HasColumnType("int");

                    b.Property<bool>("Download")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Upload")
                        .HasColumnType("bit");

                    b.HasKey("CodUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PexIM.Models.UsuariosEstados", b =>
                {
                    b.Property<int>("CodUsuarioEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CodEstado")
                        .HasColumnType("int");

                    b.Property<int?>("CodUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.HasKey("CodUsuarioEstado");

                    b.ToTable("UsuariosEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
